server:
    port: 7443        

spring:
    jackson:
        serialization:
            write-dates-as-timestamps: false

okta:
    oauth2:
        issuer: https://dev-06608405.okta.com/oauth2/default
        # issuer: https://phmic.okta.com